# Generated by Django 5.2.12 on 2026-04-05 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pembina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LaporanEkskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('materi', models.TextField()),
                ('dokumentasi', models.ImageField(blank=True, upload_to='laporan_foto/')),
                ('jumlah_santri', models.IntegerField()),
                ('diinput_pada', models.DateTimeField(auto_now_add=True)),
                ('ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ekskul')),
            ],
        ),
    ]
