# Generated by Django 5.2.12 on 2026-04-05 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekskul',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ekskul',
            name='jumlah_santri',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ekskul',
            name='nama_pembina',
            field=models.CharField(default='Admin', max_length=100),
            preserve_default=False,
        ),
    ]
