# Generated by Django 5.2.12 on 2026-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ekskul_created_at_ekskul_jumlah_santri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporanekskul',
            name='dokumentasi',
            field=models.ImageField(blank=True, null=True, upload_to='dokumentasi/'),
        ),
    ]
